In [1]:
import pandas as pd
import numpy as np

In [2]:
# crianção de dataFrames a partir de um array

In [3]:
arr = np.random.randint(10,55,size=(4,4))

In [4]:
arr

array([[22, 13, 28, 30],
       [23, 25, 46, 12],
       [48, 33, 29, 32],
       [15, 18, 52, 50]])

In [9]:
df1 = pd.DataFrame(data=arr,index= ['A', 'B', 'C','D'],columns = ['w','x','y','z'])

In [10]:
df1

    w   x   y   z
A  22  13  28  30
B  23  25  46  12
C  48  33  29  32
D  15  18  52  50

In [11]:
#Crianção de DataFrames a partir de listas // temos que criar lista dentro de lista se nao pode dar erro!

In [13]:
lista = [[10,20,30,40,50],[60,70,80,90,100]]

In [14]:
df2 = pd.DataFrame(data=lista)

In [15]:
df2

    0   1   2   3    4
0  10  20  30  40   50
1  60  70  80  90  100

In [16]:
# criação de DataFrame através de um dicionairio

In [35]:
dados = {'Produtos':['Videogame', 'PC', 'Teclado', 'Mouse', 'Microfone'], 'PREÇO':[2600.00, 2450.90, 99.90, 75, 129.99],'Custo':[2000,1950.99,54,39.80,79.75]}

In [36]:
df3 = pd.DataFrame(data=dados)

In [37]:
df3

    Produtos    PREÇO    Custo
0  Videogame  2600.00  2000.00
1         PC  2450.90  1950.99
2    Teclado    99.90    54.00
3      Mouse    75.00    39.80
4  Microfone   129.99    79.75

In [38]:
# calculando lucro sobre o produto

In [39]:
df3['Lucro'] = df3['PREÇO'] - df3['Custo']

In [40]:
df3

    Produtos    PREÇO    Custo   Lucro
0  Videogame  2600.00  2000.00  600.00
1         PC  2450.90  1950.99  499.91
2    Teclado    99.90    54.00   45.90
3      Mouse    75.00    39.80   35.20
4  Microfone   129.99    79.75   50.24