In [13]:
import pandas as pd
import numpy as np
np.random.seed(100)

In [14]:
indices = ['Janeiro', 'Março', 'Maio', 'Julho', 'Agosto', 'Outubro', 'Dezembro']

In [15]:
colunas = np.arange(1,32)

In [16]:
colunas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])

In [17]:
dados = np.random.randint(492,2050,size=(7,31))

In [18]:
dados

array([[2036, 1284,  571,  842,  545, 2042, 1294, 1501, 1244,  772, 1744,
        1832, 1404, 2023, 1609,  578,  878,  907, 1389, 1657, 1249, 1104,
        1520, 1095, 1327,  627,  541, 1947,  809, 1274, 1459],
       [1255, 1852,  494, 1381, 1109,  970, 1919,  555, 1697,  775, 1754,
        1885, 1436, 1819, 1298,  664,  766,  684, 1444, 1422,  929,  765,
        2041, 1110, 1546,  509, 1569,  560,  980, 1863,  967],
       [1185, 1338, 1516,  505, 1701, 1976,  854,  623, 1074, 1728,  886,
        1731, 2018,  987, 1135, 1365, 1692, 1696,  528, 1331,  530, 1730,
        1610, 1230, 1686, 1344,  587, 1592,  806,  594, 1430],
       [ 898, 1772, 1254,  718, 1407,  688,  938, 1310, 1968,  911,  899,
        1257, 2037, 1436, 2012,  901, 1954,  754, 1638, 1702, 1811,  778,
        1381, 1070,  735, 1412,  931,  765, 1305, 2001,  581],
       [ 921, 1295, 1532, 2040, 1982, 1113, 1583,  712, 1739, 1280,  630,
        1268,  965, 1204, 1930, 1505, 1865, 1379, 1048, 1761, 1573,  875,
        1260, 1186, 1480, 1905, 1951,  838,  526,  943, 1354],
       [1186, 1593,  704,  877, 1530, 1805,  640,  660, 1993,  934, 1288,
        1214, 1994, 1006, 1067, 1373, 1646, 1731,  637, 1753, 1766,  969,
        1228,  566, 1953, 1583, 1160, 1598, 1490, 1917, 1145],
       [1085, 1377, 1285, 1710, 1147,  856,  614,  503, 1105, 1496,  530,
        1315,  805,  579, 1183, 1246,  998, 1185, 1197, 1814,  664,  636,
        1698,  675,  575,  994, 1872, 1252, 1250, 1505,  605]])

In [19]:
df = pd.DataFrame(data=dados, index=indices, columns = colunas)

In [20]:
df

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Janeiro,2036,1284,571,842,545,2042,1294,1501,1244,772,...,1104,1520,1095,1327,627,541,1947,809,1274,1459
Março,1255,1852,494,1381,1109,970,1919,555,1697,775,...,765,2041,1110,1546,509,1569,560,980,1863,967
Maio,1185,1338,1516,505,1701,1976,854,623,1074,1728,...,1730,1610,1230,1686,1344,587,1592,806,594,1430
Julho,898,1772,1254,718,1407,688,938,1310,1968,911,...,778,1381,1070,735,1412,931,765,1305,2001,581
Agosto,921,1295,1532,2040,1982,1113,1583,712,1739,1280,...,875,1260,1186,1480,1905,1951,838,526,943,1354
Outubro,1186,1593,704,877,1530,1805,640,660,1993,934,...,969,1228,566,1953,1583,1160,1598,1490,1917,1145
Dezembro,1085,1377,1285,1710,1147,856,614,503,1105,1496,...,636,1698,675,575,994,1872,1252,1250,1505,605

In [21]:
# QUANTO VENDEU NO DIA 10 DE TODOS OS MESES ?

In [22]:
df[10]

Janeiro      772
Março        775
Maio        1728
Julho        911
Agosto      1280
Outubro      934
Dezembro    1496
Name: 10, dtype: int64

In [23]:
#quanto vendeu no dia 10,20,30 de todos os meses ?

In [24]:
df[[10,20,30]]

            10    20    30
Janeiro    772  1657  1274
Março      775  1422  1863
Maio      1728  1331   594
Julho      911  1702  2001
Agosto    1280  1761   943
Outubro    934  1753  1917
Dezembro  1496  1814  1505

In [25]:
#quanto vendeu no dia 15/março ?

In [27]:
df[15]['Março']

1298

In [28]:
#quanto vendeu nos meses de Janeiro, Março e Maio ?

In [29]:
df[0:3]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Janeiro,2036,1284,571,842,545,2042,1294,1501,1244,772,...,1104,1520,1095,1327,627,541,1947,809,1274,1459
Março,1255,1852,494,1381,1109,970,1919,555,1697,775,...,765,2041,1110,1546,509,1569,560,980,1863,967
Maio,1185,1338,1516,505,1701,1976,854,623,1074,1728,...,1730,1610,1230,1686,1344,587,1592,806,594,1430

In [30]:
#quanto vendeu nos meses de Julho, Agosto e Outubro nos dias 25 a 31 ?

In [31]:
df.loc[['Julho', 'Agosto', 'Outubro'],[25,26,27,28,29,30,31]]

           25    26    27    28    29    30    31
Julho     735  1412   931   765  1305  2001   581
Agosto   1480  1905  1951   838   526   943  1354
Outubro  1953  1583  1160  1598  1490  1917  1145

In [33]:
df.iloc[[3,4,5],[24,25,26,27,28,29,30]]

           25    26    27    28    29    30    31
Julho     735  1412   931   765  1305  2001   581
Agosto   1480  1905  1951   838   526   943  1354
Outubro  1953  1583  1160  1598  1490  1917  1145

In [37]:
# SELEÇÃO CONDICIONAL DE DATAFRAMES

In [35]:
# retornando valores maiores do que 1000
df > 1000

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Janeiro,True,True,False,False,False,True,True,True,True,False,...,True,True,True,True,False,False,True,False,True,True
Março,True,True,False,True,True,False,True,False,True,False,...,False,True,True,True,False,True,False,False,True,False
Maio,True,True,True,False,True,True,False,False,True,True,...,True,True,True,True,True,False,True,False,False,True
Julho,False,True,True,False,True,False,False,True,True,False,...,False,True,True,False,True,False,False,True,True,False
Agosto,False,True,True,True,True,True,True,False,True,True,...,False,True,True,True,True,True,False,False,False,True
Outubro,True,True,False,False,True,True,False,False,True,False,...,False,True,False,True,True,True,True,True,True,True
Dezembro,True,True,True,True,True,False,False,False,True,True,...,False,True,False,False,False,True,True,True,True,False

In [36]:
df[df > 1000]

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Janeiro,2036.0,1284,NaN,NaN,NaN,2042.0,1294.0,1501.0,1244,NaN,...,1104.0,1520,1095.0,1327.0,NaN,NaN,1947.0,NaN,1274.0,1459.0
Março,1255.0,1852,NaN,1381.0,1109.0,NaN,1919.0,NaN,1697,NaN,...,NaN,2041,1110.0,1546.0,NaN,1569.0,NaN,NaN,1863.0,NaN
Maio,1185.0,1338,1516.0,NaN,1701.0,1976.0,NaN,NaN,1074,1728.0,...,1730.0,1610,1230.0,1686.0,1344.0,NaN,1592.0,NaN,NaN,1430.0
Julho,NaN,1772,1254.0,NaN,1407.0,NaN,NaN,1310.0,1968,NaN,...,NaN,1381,1070.0,NaN,1412.0,NaN,NaN,1305.0,2001.0,NaN
Agosto,NaN,1295,1532.0,2040.0,1982.0,1113.0,1583.0,NaN,1739,1280.0,...,NaN,1260,1186.0,1480.0,1905.0,1951.0,NaN,NaN,NaN,1354.0
Outubro,1186.0,1593,NaN,NaN,1530.0,1805.0,NaN,NaN,1993,NaN,...,NaN,1228,NaN,1953.0,1583.0,1160.0,1598.0,1490.0,1917.0,1145.0
Dezembro,1085.0,1377,1285.0,1710.0,1147.0,NaN,NaN,NaN,1105,1496.0,...,NaN,1698,NaN,NaN,NaN,1872.0,1252.0,1250.0,1505.0,NaN

In [38]:
# Preenchando valores menores com -
df[df > 1000].fillna('-')

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Janeiro,2036.0,1284,-,-,-,2042.0,1294.0,1501.0,1244,-,...,1104.0,1520,1095.0,1327.0,-,-,1947.0,-,1274.0,1459.0
Março,1255.0,1852,-,1381.0,1109.0,-,1919.0,-,1697,-,...,-,2041,1110.0,1546.0,-,1569.0,-,-,1863.0,-
Maio,1185.0,1338,1516.0,-,1701.0,1976.0,-,-,1074,1728.0,...,1730.0,1610,1230.0,1686.0,1344.0,-,1592.0,-,-,1430.0
Julho,-,1772,1254.0,-,1407.0,-,-,1310.0,1968,-,...,-,1381,1070.0,-,1412.0,-,-,1305.0,2001.0,-
Agosto,-,1295,1532.0,2040.0,1982.0,1113.0,1583.0,-,1739,1280.0,...,-,1260,1186.0,1480.0,1905.0,1951.0,-,-,-,1354.0
Outubro,1186.0,1593,-,-,1530.0,1805.0,-,-,1993,-,...,-,1228,-,1953.0,1583.0,1160.0,1598.0,1490.0,1917.0,1145.0
Dezembro,1085.0,1377,1285.0,1710.0,1147.0,-,-,-,1105,1496.0,...,-,1698,-,-,-,1872.0,1252.0,1250.0,1505.0,-

In [40]:
#pegando alguns meses maiores que 1000
df[df > 1000][0:3].fillna('-')

,1,2,3,4,5,6,7,8,9,10,...,22,23,24,25,26,27,28,29,30,31
Janeiro,2036.0,1284,-,-,-,2042.0,1294.0,1501.0,1244,-,...,1104.0,1520,1095.0,1327.0,-,-,1947.0,-,1274.0,1459.0
Março,1255.0,1852,-,1381.0,1109.0,-,1919.0,-,1697,-,...,-,2041,1110.0,1546.0,-,1569.0,-,-,1863.0,-
Maio,1185.0,1338,1516.0,-,1701.0,1976.0,-,-,1074,1728.0,...,1730.0,1610,1230.0,1686.0,1344.0,-,1592.0,-,-,1430.0

In [42]:
df[df > 1000][:][[1,2,3,4,5]].fillna('-')

               1     2       3       4       5
Janeiro   2036.0  1284       -       -       -
Março     1255.0  1852       -  1381.0  1109.0
Maio      1185.0  1338  1516.0       -  1701.0
Julho          -  1772  1254.0       -  1407.0
Agosto         -  1295  1532.0  2040.0  1982.0
Outubro   1186.0  1593       -       -  1530.0
Dezembro  1085.0  1377  1285.0  1710.0  1147.0